name: Generate Snake Animation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          
